### ISSUE TITLE
Reimplimenet ability to restrict updating branches directly

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/.github#265] opened 2024-06-03 23:46 UTC
Branch protection rulesets were added to all supported repos on [this issue](https://github.com/silverstripe/.github/issues/198)

The ended up breaking automated merge-ups so part of the ruleset was reverted on [this issue](https://github.com/silverstripe/.github/issues/264)

This meant that there was again no need to have bypass ability to directly pushing to a branch

## Notes
- We may wish to not actually do this card if the solution turns out to be too convoluted, and we just live the the fact that people with write permissions can directly push to branches

## Acceptance criteria
- Users without bypass permissions cannot push directly to branches
- Automated merge-ups work

**Comment by maxime-rainville** [comment] 2024-07-02 22:36
Duplicate of #260

**Closed by maxime-rainville** 2024-07-02 22:36 UTC
Labels: type/other
